#!/bin/bash
echo "=========================================="
echo "Gallery Desktop Application Launcher"
echo "=========================================="
echo ""
echo "Requirements:"
echo "  - Java 21+"
echo "  - JavaFX 24"
echo "  - Maven"
echo ""
echo "To run the application:"
echo "  mvn clean javafx:run"
echo ""
echo "Or build and run:"
echo "  mvn clean package"
echo "  java --module-path /path/to/javafx/lib --add-modules javafx.controls,javafx.fxml -jar target/gallery-desktop-1.0.0-SNAPSHOT.jar"
echo ""
echo "Keyboard Shortcuts:"
echo "  ← → : Previous/Next image"
echo "  Space : Slideshow play/pause"
echo "  F11 : Fullscreen"
echo "  ESC : Exit fullscreen"
echo "  Ctrl + Wheel : Zoom in/out"
echo "  Delete : Delete current image"
echo "  Home/End : First/Last image"
echo ""
